[project]
name = "aiops-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk[extensions]>=2.10.0",
    "google-cloud-aiplatform>=2.2.0",
    "jinja2>=3.1.6",
    "mcp>=2.2.0",
    "nltk>=3.10.3",
    "numpy>=2.5.3",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.3",
    "rouge-score>=0.1.2",
    "tabulate>=0.10.0",
]
